monitor.alsa.rules = [
  # Make RodeCaster Pro II the preferred default sink (output)
  {
    matches = [
      {
        node.name = "~alsa_output.usb-R__DE_R__DECaster_Pro_II*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 2000
        priority.session = 2000
      }
    }
  }
  # Make RodeCaster Pro II the preferred default source (input)
  {
    matches = [
      {
        node.name = "~alsa_input.usb-R__DE_R__DECaster_Pro_II*"
      }
    ]
    actions = {
      update-props = {
        priority.driver = 2000
        priority.session = 2000
      }
    }
  }
]
